-- MySQL Script generated by MySQL Workbench
-- 11/24/16 18:33:19
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mealPalDb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mealPalDb` ;

-- -----------------------------------------------------
-- Schema mealPalDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mealPalDb` DEFAULT CHARACTER SET utf8 ;
USE `mealPalDb` ;

-- -----------------------------------------------------
-- Table `mealPalDb`.`Ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mealPalDb`.`Ingredients` ;

CREATE TABLE IF NOT EXISTS `mealPalDb`.`Ingredients` (
  `idIngredients` INT NOT NULL,
  `IngredientsName` VARCHAR(45) NOT NULL,
  `LikePercentage` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`idIngredients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mealPalDb`.`Meal_Prefference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mealPalDb`.`Meal_Prefference` ;

CREATE TABLE IF NOT EXISTS `mealPalDb`.`Meal_Prefference` (
  `idMeal_Prefference` INT NOT NULL,
  `MealType` VARCHAR(10) NOT NULL,
  `MealPortion` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`idMeal_Prefference`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mealPalDb`.`Customer_Prefference`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mealPalDb`.`Customer_Prefference` ;

CREATE TABLE IF NOT EXISTS `mealPalDb`.`Customer_Prefference` (
  `idCustomer_Prefference` INT NOT NULL,
  `idCustomer` INT NOT NULL,
  `Ingredients_idIngredients` INT NOT NULL,
  `Meal_Prefference_idMeal_Prefference` INT NOT NULL,
  PRIMARY KEY (`idCustomer_Prefference`, `Ingredients_idIngredients`, `Meal_Prefference_idMeal_Prefference`),
  CONSTRAINT `fk_Customer_Prefference_Ingredients1`
    FOREIGN KEY (`Ingredients_idIngredients`)
    REFERENCES `mealPalDb`.`Ingredients` (`idIngredients`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_Prefference_Meal_Prefference1`
    FOREIGN KEY (`Meal_Prefference_idMeal_Prefference`)
    REFERENCES `mealPalDb`.`Meal_Prefference` (`idMeal_Prefference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Customer_Prefference_Ingredients1_idx` ON `mealPalDb`.`Customer_Prefference` (`Ingredients_idIngredients` ASC);

CREATE INDEX `fk_Customer_Prefference_Meal_Prefference1_idx` ON `mealPalDb`.`Customer_Prefference` (`Meal_Prefference_idMeal_Prefference` ASC);


-- -----------------------------------------------------
-- Table `mealPalDb`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mealPalDb`.`Customer` ;

CREATE TABLE IF NOT EXISTS `mealPalDb`.`Customer` (
  `idCustomer` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Phonenum` CHAR(10) NOT NULL,
  `Email` VARCHAR(45) NULL,
  `Work_address` VARCHAR(100) NULL,
  `Customer_Prefference_idCustomer_Prefference` INT NOT NULL,
  PRIMARY KEY (`idCustomer`, `Customer_Prefference_idCustomer_Prefference`),
  CONSTRAINT `fk_Customer_Customer_Prefference1`
    FOREIGN KEY (`Customer_Prefference_idCustomer_Prefference`)
    REFERENCES `mealPalDb`.`Customer_Prefference` (`idCustomer_Prefference`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Customer_Customer_Prefference1_idx` ON `mealPalDb`.`Customer` (`Customer_Prefference_idCustomer_Prefference` ASC);


-- -----------------------------------------------------
-- Table `mealPalDb`.`MealPass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mealPalDb`.`MealPass` ;

CREATE TABLE IF NOT EXISTS `mealPalDb`.`MealPass` (
  `idMealPass` INT NOT NULL,
  `PlanName` VARCHAR(45) NOT NULL,
  `CycleStartDate` VARCHAR(20) NOT NULL,
  `CycleEndDate` VARCHAR(20) NOT NULL,
  `MealTotal` INT NOT NULL,
  `MealUsed` INT NOT NULL,
  `Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idMealPass`, `Customer_idCustomer`),
  CONSTRAINT `fk_MealPass_Customer`
    FOREIGN KEY (`Customer_idCustomer`)
    REFERENCES `mealPalDb`.`Customer` (`idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_MealPass_Customer_idx` ON `mealPalDb`.`MealPass` (`Customer_idCustomer` ASC);


-- -----------------------------------------------------
-- Table `mealPalDb`.`Restaurants`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mealPalDb`.`Restaurants` ;

CREATE TABLE IF NOT EXISTS `mealPalDb`.`Restaurants` (
  `idRestaurants` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Address` VARCHAR(100) NOT NULL,
  `Rating` VARCHAR(45) NULL,
  `Latitude` DECIMAL(3,3) NULL,
  `Longitude` DECIMAL(3,3) NULL,
  `MealPass_idMealPass` INT NOT NULL,
  `MealPass_Customer_idCustomer` INT NOT NULL,
  PRIMARY KEY (`idRestaurants`, `MealPass_idMealPass`, `MealPass_Customer_idCustomer`),
  CONSTRAINT `fk_Restaurants_MealPass1`
    FOREIGN KEY (`MealPass_idMealPass` , `MealPass_Customer_idCustomer`)
    REFERENCES `mealPalDb`.`MealPass` (`idMealPass` , `Customer_idCustomer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Restaurants_MealPass1_idx` ON `mealPalDb`.`Restaurants` (`MealPass_idMealPass` ASC, `MealPass_Customer_idCustomer` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
